name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (x.y.z-abcN e.g. 4.5.6-beta1)'
        required: true
      real_op:
        description: 'Push changes'
        type: boolean
        default: false
        required: true
      git_push_args:
        description: 'For example: --force-with-lease'
        type: string
        default: ''
        required: false

jobs:
  preparation:
    runs-on: ubuntu-26.04

    steps:
      - name: Check for admin-ui-assets package
        uses: ibexa/gh-workflows/actions/check-composer-package@main
        with:
          package: ibexa/admin-ui-assets
          version: v${{ inputs.version }}

  action:
    needs: preparation
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set dependency versions, commit, tag and push
        uses: ibexa/gh-workflows/actions/create-metapackage-tag@main
        with:
          version: ${{ inputs.version }}
          pin-packages: ibexa/admin-ui-assets
          real-op: ${{ inputs.real_op }}
          git-push-args: ${{ inputs.git_push_args }}
          gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
          gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
          satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
          satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}
