name: Nightly browser tests
on:
    schedule:
        # Run tests every morning
        - cron: "0 2 * * *"
    workflow_dispatch: ~

jobs:
    nightly:
        runs-on: ubuntu-26.04
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                repository:
                    - ibexa/oss
                    - ibexa/headless
                    - ibexa/experience
                    - ibexa/commerce
                branch:
                    - "4.6"
                    - "5.0"
                    - "6.0"
        steps:
            - uses: actions/create-github-app-token@v3
              id: generate_token
              with:
                  client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  owner: ${{ github.repository_owner }}
            - name: Trigger workflow
              shell: bash
              run: |
                  gh api --method POST "/repos/${{ matrix.repository }}/actions/workflows/browser-tests.yml/dispatches" \
                    -f ref="${{ matrix.branch }}" \
                    -f "inputs[send-success-notification]=false"
              env:
                  GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
