name: Post release

on:
  workflow_run:
    workflows: ["Call Create Release for tag Workflow"]
    types:
      - completed

jobs:
  call-post-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ibexa/gh-workflow/.github/workflows/post_release.yml@main
    secrets: inherit
