name: Post release

on:
  workflow_run:
    workflows: ["Call Create Release for tag Workflow"]
    types:
      - completed

jobs:
  call-post-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ibexa/gh-workflows/.github/workflows/post_release.yaml@main
    with:
      tag: ${{ github.event.workflow_run.head_branch }}
    secrets: inherit
